"""Nuevo sistema de roles y permisos

Revision ID: 1e4bf5c6ff32
Revises: f74a3d75dadc
Create Date: 2026-08-20 17:25:47.760020

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e4bf5c6ff32'
down_revision: Union[str, Sequence[str], None] = 'f74a3d75dadc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
