"""Esquema de login primera parte

Revision ID: 320c549d58b3
Revises: 2227fbd3ae2e
Create Date: 2026-08-17 23:04:16.690720

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '320c549d58b3'
down_revision: Union[str, Sequence[str], None] = '2227fbd3ae2e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
