"""Add advanced RBAC

Revision ID: f74a3d75dadc
Revises: e36547b11d72
Create Date: 2026-08-20 17:24:23.318196

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f74a3d75dadc'
down_revision: Union[str, Sequence[str], None] = 'e36547b11d72'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('actions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_actions_name'), 'actions', ['name'], unique=True)
    op.create_table('permission_groups',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_permission_groups_name'), 'permission_groups', ['name'], unique=True)
    op.create_table('resources',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resources_name'), 'resources', ['name'], unique=True)
    op.add_column('permissions', sa.Column('action_id', sa.String(length=36), nullable=False))
    op.add_column('permissions', sa.Column('resource_id', sa.String(length=36), nullable=False))
    op.add_column('permissions', sa.Column('group_id', sa.String(length=36), nullable=True))
    op.drop_index(op.f('ix_permissions_name'), table_name='permissions')
    op.create_foreign_key(None, 'permissions', 'permission_groups', ['group_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'permissions', 'actions', ['action_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'permissions', 'resources', ['resource_id'], ['id'], ondelete='CASCADE')
    op.drop_column('permissions', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('permissions', sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'permissions', type_='foreignkey')
    op.drop_constraint(None, 'permissions', type_='foreignkey')
    op.drop_constraint(None, 'permissions', type_='foreignkey')
    op.create_index(op.f('ix_permissions_name'), 'permissions', ['name'], unique=True)
    op.drop_column('permissions', 'group_id')
    op.drop_column('permissions', 'resource_id')
    op.drop_column('permissions', 'action_id')
    op.drop_index(op.f('ix_resources_name'), table_name='resources')
    op.drop_table('resources')
    op.drop_index(op.f('ix_permission_groups_name'), table_name='permission_groups')
    op.drop_table('permission_groups')
    op.drop_index(op.f('ix_actions_name'), table_name='actions')
    op.drop_table('actions')
    # ### end Alembic commands ###
